package main

import (
	"flag"
	fmt "fmt"
	"github.com/coffeemakr/httpsify/hsts"
	"github.com/coffeemakr/httpsify/httpseverywhere"
	"log"
	"os"
)

func writeHostsFile(hosts []string, filename string) error {
	fp, err := os.Create(filename)
	defer fp.Close()
	if err != nil {
		return err
	}
	for _, host := range hosts {
		fmt.Fprintln(fp, host)
	}
	return nil
}

func main() {
	var rulesPath string
	var hostsFile string
	var subdomainsFile string
	var packageName = "simple"
	var codeFile string
	flag.StringVar(&rulesPath, "https-everywhere-rules", "", "Path to the rules")
	flag.StringVar(&hostsFile, "domains-out", "", "Path to the rules")
	flag.StringVar(&subdomainsFile, "subdomains-out", "", "Path to the rules")
	flag.StringVar(&codeFile, "code-out", "", "Path to the rules")
	flag.Parse()

	log.Println("Loading https everywhere...")
	rules, err := httpseverywhere.Parse(rulesPath)
	if err != nil {
		log.Fatalln(err)
	}
	log.Println("Loading hsts...")
	hstsRules, err := hsts.LoadHstsPreload()
	if err != nil {
		log.Fatalln(err)
	}

	rules.Add(hstsRules)
	hstsRules = nil

	if subdomainsFile != "" {
		err = writeHostsFile(rules.SimpleSubdomainTargets(), subdomainsFile)
		if err != nil {
			log.Fatalln(err)
		}
	}
	if hostsFile != "" {
		err = writeHostsFile(rules.SimpleTargets(), hostsFile)
		if err != nil {
			log.Fatalln(err)
		}
	}

	if codeFile != "" {
		f, err := os.Create(codeFile)
		if err != nil {
			log.Fatalln(err)
		}
		defer f.Close()
		_, _ = fmt.Fprintf(f, `// Code generated by go run generate.go. DO NOT EDIT.
//)
// This file was generated from the Chromium HSTS preloaded list")

package %s

import (
	"github.com/coffeemakr/httpsify"
)

var SimpleRules = httpsify.NewRuleCollection()

func init() {
`, packageName)

		_, _ = fmt.Fprintln(f, "    var includeSubdomainsNames = []string { ")
		for _, name := range rules.SimpleSubdomainTargets() {
			_, _ = fmt.Fprintf(f, "        %#v,\n", name)
		}
		_, _ = fmt.Fprintln(f, "    }")
		_, _ = fmt.Fprintln(f, "    var names = []string { ")
		for _, name := range rules.SimpleTargets() {
			_, _ = fmt.Fprintf(f, "        %#v,\n", name)
		}
		_, _ = fmt.Fprintln(f, "    }")

		_, _ = fmt.Fprintf(f, `
	SimpleRules.AddSimpleHosts(includeSubdomainsNames, true)
	SimpleRules.AddSimpleHosts(names, false)
}
`)
	}
}
